package com.newchinese.smartmeeting.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.newchinese.smartmeeting.entity.bean.NoteRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTE_RECORD".
*/
public class NoteRecordDao extends AbstractDao<NoteRecord, Long> {

    public static final String TABLENAME = "NOTE_RECORD";

    /**
     * Properties of entity NoteRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClassifyName = new Property(1, String.class, "classifyName", false, "CLASSIFY_NAME");
        public final static Property ClassifyCode = new Property(2, String.class, "classifyCode", false, "CLASSIFY_CODE");
    }

    private DaoSession daoSession;


    public NoteRecordDao(DaoConfig config) {
        super(config);
    }
    
    public NoteRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTE_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CLASSIFY_NAME\" TEXT," + // 1: classifyName
                "\"CLASSIFY_CODE\" TEXT);"); // 2: classifyCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTE_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NoteRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String classifyName = entity.getClassifyName();
        if (classifyName != null) {
            stmt.bindString(2, classifyName);
        }
 
        String classifyCode = entity.getClassifyCode();
        if (classifyCode != null) {
            stmt.bindString(3, classifyCode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NoteRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String classifyName = entity.getClassifyName();
        if (classifyName != null) {
            stmt.bindString(2, classifyName);
        }
 
        String classifyCode = entity.getClassifyCode();
        if (classifyCode != null) {
            stmt.bindString(3, classifyCode);
        }
    }

    @Override
    protected final void attachEntity(NoteRecord entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NoteRecord readEntity(Cursor cursor, int offset) {
        NoteRecord entity = new NoteRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // classifyName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // classifyCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NoteRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClassifyName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setClassifyCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NoteRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NoteRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NoteRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
